version: '3.8'
x-common-env:
  - LOGGER_LEVEL=debug
  - GOPATH=/src/.dockerbuild/gopath
  - GOCACHE=/src/.dockerbuild/gocache
  - STATIC_FILES=/src/assets
x-golang_base:
  image: 'golang:1.14'
  working_dir: /src
  environment:
    - LOGGER_LEVEL=debug
    - GOPATH=/src/.dockerbuild/gopath
    - GOCACHE=/src/.dockerbuild/gocache
  volumes:
    - '.:/src'
services:
  envoy:
    image: 'envoyproxy/envoy-dev:b055dd082c0a49525a97cea6604ac1323a55d2fb'
    volumes:
      - './setting/envoy_config.yaml:/etc/envoy/envoy.yaml'
    ports:
      - '10000:10000'
      - '10001:10001'
    networks:
      - mockingbird-internal
  mockingbird:
    image: 'mockingbird:latest'
    build:
      context: .
    ports:
      - '3000:3000'
      - '4000:4000'
    networks:
      - mockingbird-internal
  build:
    image: 'golang:1.14'
    working_dir: /src
    environment:
      - LOGGER_LEVEL=debug
      - GOPATH=/src/.dockerbuild/gopath
      - GOCACHE=/src/.dockerbuild/gocache
    volumes:
      - '.:/src'
    command:
      - make
  build-web: # This command will take more than 14min... 
    image: node:12-alpine
    working_dir: /src/web
    volumes:
      - '.:/src'
    command:
      - yarn 
      - run 
      - build:prod

networks:
  mockingbird-internal:
    name: mockingbird-internal
