name: Publish Docker image
on:
  push:
    branches: main
jobs:
  push_to_registry:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      # build web
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --pure-lockfile
        working-directory: ./web
      - run: yarn build
        working-directory: ./web
      # build management server
      - name: Build and Push 
        run: sh ./build.sh
