name: Release
on:
  push:
    branch: main
    tags: 
      - v.*
      - beta-v*
jobs:
  release:
    name: Building and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      # build web
      - name: Setup Node 12 environment
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Dep
        run: yarn install --pure-lockfile
        working-directory: ./web
      - name: Build the Web Assets
        run: yarn build
        working-directory: ./web
      # build management server
      - name: Build The Server Image and Push to DockerHub
        run: sh ./build.sh
      # Notification
      - name: Discord bot
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: ${{ github.workflow }}
          description: "Build image and deploy to DockerHub"
          username: GitHub Actions
