name: Publish Docker image
on:
  push:
    branches: main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      # build web
      - name: Install Web Dep
        uses: borales/actions-yarn@v2.0.0
        working-directory: ./web
        with:
          cmd: --pure-lockfile
      - name: Build assets/admin
        uses: borales/actions-yarn@v2.0.0
        working-directory: ./web
        with:
          cmd: build
      # build management server
      - name: Build and Push 
        run: sh ./build.sh
