name: Publish Docker image
on:
  push:
    branches: release
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      # build web
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --pure-lockfile
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      # build management server
      - uses: borales/actions-yarn@v2.0.0
      - name: Build and Push 
        run: sh ./build.sh
